class BurgerSample:

    BUN_NAME = 'red bun'
    BUN_PRICE = 300
    SAUCE_NAME = 'sour cream'
    SAUCE_PRICE = 200
    FILLING_NAME = 'sausage'
    FILLING_PRICE = 300
    BUN_NAME2 = 'white bun'
    BUN_PRICE2 = 200
    SAUCE_NAME2 = 'chili sauce'
    SAUCE_PRICE2 = 300
    FILLING_NAME2 = 'dinosaur'
    FILLING_PRICE2 = 200
    BURGER1 = (BUN_NAME, BUN_PRICE, SAUCE_NAME, SAUCE_PRICE, FILLING_NAME, FILLING_PRICE, 1100)
    BURGER2 = (BUN_NAME2, BUN_PRICE2, SAUCE_NAME2, SAUCE_PRICE2, FILLING_NAME2, FILLING_PRICE2, 900)
